In [23]:
# importando a biblioteca pandas
import pandas as pd
# lendo o arquivo excel e armazenando na variável emissoes_gases
emissoes_gases = pd.read_excel('C:\\Users\\eleil\\OneDrive\\Documents\\GitHub\\Estudo-e-Projetos-Alura\\Python para Data Sciense\\Pandas\\Selecionando e Agrupando dados\\1-SEEG10_GERAL-BR_UF_2022.10.27-FINAL-SITE.xlsx', sheet_name='GEE Estados')
emissoes_gases

C:\Users\eleil\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,Nível 1 - Setor,Nível 2,Nível 3,Nível 4,Nível 5,Nível 6,Emissão / Remoção / Bunker,Gás,Estado,Atividade Econômica,Produto,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Processos Industriais,Indústria Química,Produção de ABS,NaN,NaN,NaN,Emissão,COVNM (t),SP,OUTRA_IND,NaN,0.0,0.000,0.000,0.000,0.00,16.728,1.552576e+02,1.629552e+02,2.314992e+02,3.082848e+02,3.688864e+02,291.040,311.304,571.200,670.480,6.811333e+02,6.917867e+02,702.440,7.130933e+02,7.237467e+02,734.400,707.200,761.600,870.400,870.400,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,8.976000e+02,897.600
1,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,N2O (t),SP,OUTRA_IND,NaN,6210.0,6116.580,7747.650,8276.580,9366.30,9675.720,1.299105e+04,1.389312e+04,1.448847e+04,1.459296e+04,1.437264e+04,13611.240,13854.240,14731.470,11670.480,1.025001e+04,1.193292e+04,11307.330,1.108269e+04,1.132488e+04,8630.000,11250.000,10410.000,13840.000,13990.000,15080.000,11220.000,9660.000,16750.000,16620.000,17510.000,13900.000,17800.000,16190.000,23480.000,20290.000,22310.000,570.000,370.000,140.000,130.000,130.000,130.000,130.000,130.000,130.000,130.000,130.000,130.000,130.000,1.300000e+02,130.000
2,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,CO (t),SP,OUTRA_IND,NaN,368.0,362.464,459.120,490.464,555.04,573.376,7.698400e+02,8.232960e+02,8.585760e+02,8.647680e+02,8.517120e+02,806.592,820.992,872.976,691.584,6.074080e+02,7.071360e+02,670.064,6.567520e+02,6.711040e+02,511.216,666.816,616.608,820.224,829.200,893.824,664.864,572.272,992.880,985.152,1037.792,823.776,1054.896,959.664,1391.328,1202.352,1321.824,1421.808,1360.336,1395.136,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1.380576e+03,1380.576
3,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,NOx (t),SP,OUTRA_IND,NaN,115.0,113.270,143.475,153.270,173.45,179.180,2.405750e+02,2.572800e+02,2.683050e+02,2.702400e+02,2.661600e+02,252.060,256.560,272.805,216.120,1.898150e+02,2.209800e+02,209.395,2.052350e+02,2.097200e+02,159.755,208.380,192.690,256.320,259.125,279.320,207.770,178.835,310.275,307.860,324.310,257.430,329.655,299.895,434.790,375.735,413.070,444.315,425.105,435.980,431.430,431.430,431.430,431.430,431.430,431.430,431.430,431.430,431.430,431.430,4.314300e+02,431.430
4,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,CO2e (t) GWP-AR2,SP,OUTRA_IND,NaN,1925100.0,1896139.800,2401771.500,2565739.800,2903553.00,2999473.200,4.027226e+06,4.306867e+06,4.491426e+06,4.523818e+06,4.455518e+06,4219484.400,4294814.400,4566755.700,3617848.800,3.177503e+06,3.699205e+06,3505272.300,3.435634e+06,3.510713e+06,2675300.000,3487500.000,3227100.000,4290400.000,4336900.000,4674800.000,3478200.000,2994600.000,5192500.000,5152200.000,5428100.000,4309000.000,5518000.000,5018900.000,7278800.000,6289900.000,6916100.000,176700.000,114700.000,43400.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,4.030000e+04,40300.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103307,Mudança de Uso da Terra e Floresta,Queimadas Não Associadas a Desmatamento,Pantanal,NaN,NaN,NaN,Emissão NCI,CO2e (t) GTP-AR6,BR,NaN,NaN,0.0,0.000,0.000,0.000,0.00,0.000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000000e+00,0.000000e+00,0.000,0.000000e+00,0.000000e+00,1772147.600,4058058.500,1260131.100,6193118.500,1665738.800,4888591.400,2942384.900,2034731.800,2273588.100,8697254.500,2009104.000,4543859.200,6206405.500,1604097.500,3753625.000,6183802.700,1760922.800,5330633.500,2382039.700,2126742.900,3501963.100,1764284.600,2731963.400,1091033.900,853275.300,1003731.400,1615000.600,1552258.800,216231.900,2805297.300,9.659261e+06,0.000
103308,Mudança de Uso da Terra e Floresta,Queimadas Não Associadas a Desmatamento,Pantanal,NaN,NaN,NaN,Emissão NCI,CO2e (t) GWP-AR2,BR,NaN,NaN,0.0,0.000,0.000,0.000,0.00,0.000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000000e+00,0.000000e+00,0.000,0.000000e+00,0.000000e+00,1904928.000,4402056.000,1337305.000,6741647.000,1763156.000,5280024.000,3144254.000,2140463.000,2405490.000,9451859.000,2130275.000,4867998.000,6747519.000,1662643.000,3989909.000,6669940.000,1838932.000,5731377.000,2515946.000,2236108.000,3731857.000,1858054.000,2921341.000,1144504.000,896685.000,1074717.000,1763431.000,1706030.000,252599.000,3105007.000,1.053571e+07,0.000
103309,Mudança de Uso da Terra e Floresta,Queimadas Não Associadas a Desmatamento,Pantanal,NaN,NaN,NaN,Emissão NCI,CO2e (t) GWP-AR4,BR,NaN,NaN,0.0,0.000,0.000,0.000,0.00,0.000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000000e+00,0.000000e+00,0.000,0.000000e+00,0.000000e+00,1922744.000,4451684.000,1347469.000,6818851.000,1776712.000,5339964.000,3171702.000,2154947.000,2423214.000,9560911.000,2146447.000,4915626.000,6826271.000,1670491.000,4025617.000,6743172.000,1849888.000,5790605.000,2534718.000,2252596.000,3766553.000,1870962.000,2950049.000,1151848.000,902209.000,1084073.000,1782863.000,1726958.000,257507.000,3147567.000,1.067568e+07,0.000
103310,Mudança de Uso da Terra e Floresta,Queimadas Não Associadas a Desmatamento,Pantanal,NaN,NaN,NaN,Emissão NCI,CO2e (t) GWP-AR5,BR,NaN,NaN,0.0,0.000,0.000,0.000,0.00,0.000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000000e+00,0.000000e+00,0.000,0.000000e+00,0.000000e+00,1924634.000,4461881.000,1348276.000,6832162.000,1778839.000,5356863.000,3175128.000,2156906.000,2425131.000,9583564.000,2148040.000,4926555.000,6843359.000,1671313.000,4035094.000,6762312.000,1851745.000,5804642.000,2537853.000,2256922.000,3775703.000,1872795.000,2957780.000,1152868.000,902368.000,1084826.000,1784237.000,1729598.000,258068.000,3155415.000,1.072232e+07,0.000
103311,Mudança de Uso da Terra e Floresta,Queimadas Não Associadas a Desmatamento,Pantanal,NaN,NaN,NaN,Emissão NCI,CO2e (t) GWP-AR6,BR,NaN,NaN,0.0,0.000,0.000,0.000,0.00,0.000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000000e+00,0.000000e+00,0.000,0.000000e+00,0.000000e+00,1922570.000,4455104.000,1347155.000,6822151.000,1777125.000,5347723.000,3171841.000,2155140.000,2423070.000,9568621.000,2146192.000,4919813.000,6832416.000,1670406.000,4029772.000,6751459.000,1850331.000,5796165.000,2535440.000,2254475.000,3770544.000,1871203.000,2953478.000,1151967.000,901817.000,1083792.000,1782129.000,1727086.000,257491.000,3149790.000,1.069948e+07,0.000

In [ ]:
# exibindo as primeiras linhas do DataFrame
emissoes_gases.head()

,Nível 1 - Setor,Nível 2,Nível 3,Nível 4,Nível 5,Nível 6,Emissão / Remoção / Bunker,Gás,Estado,Atividade Econômica,Produto,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Processos Industriais,Indústria Química,Produção de ABS,NaN,NaN,NaN,Emissão,COVNM (t),SP,OUTRA_IND,NaN,0.0,0.000,0.000,0.000,0.00,16.728,1.552576e+02,1.629552e+02,2.314992e+02,3.082848e+02,3.688864e+02,291.040,311.304,571.200,670.480,6.811333e+02,6.917867e+02,702.440,7.130933e+02,7.237467e+02,734.400,707.200,761.600,870.400,870.400,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600
1,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,N2O (t),SP,OUTRA_IND,NaN,6210.0,6116.580,7747.650,8276.580,9366.30,9675.720,1.299105e+04,1.389312e+04,1.448847e+04,1.459296e+04,1.437264e+04,13611.240,13854.240,14731.470,11670.480,1.025001e+04,1.193292e+04,11307.330,1.108269e+04,1.132488e+04,8630.000,11250.000,10410.000,13840.000,13990.000,15080.000,11220.000,9660.000,16750.000,16620.000,17510.000,13900.000,17800.000,16190.000,23480.000,20290.000,22310.000,570.000,370.000,140.000,130.000,130.000,130.000,130.000,130.000,130.000,130.000,130.000,130.000,130.000,130.000,130.000
2,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,CO (t),SP,OUTRA_IND,NaN,368.0,362.464,459.120,490.464,555.04,573.376,7.698400e+02,8.232960e+02,8.585760e+02,8.647680e+02,8.517120e+02,806.592,820.992,872.976,691.584,6.074080e+02,7.071360e+02,670.064,6.567520e+02,6.711040e+02,511.216,666.816,616.608,820.224,829.200,893.824,664.864,572.272,992.880,985.152,1037.792,823.776,1054.896,959.664,1391.328,1202.352,1321.824,1421.808,1360.336,1395.136,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576
3,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,NOx (t),SP,OUTRA_IND,NaN,115.0,113.270,143.475,153.270,173.45,179.180,2.405750e+02,2.572800e+02,2.683050e+02,2.702400e+02,2.661600e+02,252.060,256.560,272.805,216.120,1.898150e+02,2.209800e+02,209.395,2.052350e+02,2.097200e+02,159.755,208.380,192.690,256.320,259.125,279.320,207.770,178.835,310.275,307.860,324.310,257.430,329.655,299.895,434.790,375.735,413.070,444.315,425.105,435.980,431.430,431.430,431.430,431.430,431.430,431.430,431.430,431.430,431.430,431.430,431.430,431.430
4,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,CO2e (t) GWP-AR2,SP,OUTRA_IND,NaN,1925100.0,1896139.800,2401771.500,2565739.800,2903553.00,2999473.200,4.027226e+06,4.306867e+06,4.491426e+06,4.523818e+06,4.455518e+06,4219484.400,4294814.400,4566755.700,3617848.800,3.177503e+06,3.699205e+06,3505272.300,3.435634e+06,3.510713e+06,2675300.000,3487500.000,3227100.000,4290400.000,4336900.000,4674800.000,3478200.000,2994600.000,5192500.000,5152200.000,5428100.000,4309000.000,5518000.000,5018900.000,7278800.000,6289900.000,6916100.000,176700.000,114700.000,43400.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000

In [22]:
# configurando para exibir todas as colunas sem reticências
pd.set_option('display.max_columns', None)
# visualizando todas as colunas do DataFrame
emissoes_gases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103312 entries, 0 to 103311
Data columns (total 63 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Nível 1 - Setor             103312 non-null  object
 1   Nível 2                     103312 non-null  object
 2   Nível 3                     103253 non-null  object
 3   Nível 4                     90920 non-null   object
 4   Nível 5                     100788 non-null  object
 5   Nível 6                     97691 non-null   object
 6   Emissão / Remoção / Bunker  103312 non-null  object
 7   Gás                         103312 non-null  object
 8   Estado                      97374 non-null   object
 9   Atividade Econômica         102076 non-null  object
 10  Produto                     37413 non-null   object
 11  1970                        103312 non-null  float64
 12  1971                        103312 non-null  float64
 13  1972                        103312 non-null  float64
 14  1973                        103312 non-null  float64
 15  1974                        103312 non-null  float64
 16  1975                        103312 non-null  float64
 17  1976                        103312 non-null  float64
 18  1977                        103312 non-null  float64
 19  1978                        103312 non-null  float64
 20  1979                        103312 non-null  float64
 21  1980                        103312 non-null  float64
 22  1981                        103312 non-null  float64
 23  1982                        103312 non-null  float64
 24  1983                        103312 non-null  float64
 25  1984                        103312 non-null  float64
 26  1985                        103312 non-null  float64
 27  1986                        103312 non-null  float64
 28  1987                        103312 non-null  float64
 29  1988                        103312 non-null  float64
 30  1989                        103312 non-null  float64
 31  1990                        103312 non-null  float64
 32  1991                        103312 non-null  float64
 33  1992                        103312 non-null  float64
 34  1993                        103312 non-null  float64
 35  1994                        103312 non-null  float64
 36  1995                        103312 non-null  float64
 37  1996                        103312 non-null  float64
 38  1997                        103312 non-null  float64
 39  1998                        103312 non-null  float64
 40  1999                        103312 non-null  float64
 41  2000                        103312 non-null  float64
 42  2001                        103312 non-null  float64
 43  2002                        103312 non-null  float64
 44  2003                        103312 non-null  float64
 45  2004                        103312 non-null  float64
 46  2005                        103312 non-null  float64
 47  2006                        103312 non-null  float64
 48  2007                        103312 non-null  float64
 49  2008                        103312 non-null  float64
 50  2009                        103312 non-null  float64
 51  2010                        103312 non-null  float64
 52  2011                        103312 non-null  float64
 53  2012                        103312 non-null  float64
 54  2013                        103312 non-null  float64
 55  2014                        103312 non-null  float64
 56  2015                        103312 non-null  float64
 57  2016                        103312 non-null  float64
 58  2017                        103312 non-null  float64
 59  2018                        103312 non-null  float64
 60  2019                        103312 non-null  float64
 61  2020                        103312 non-null  float64
 62  2021                        103312 non-null  float64
dtypes: float64(52), object(11)
memory usage: 49.7+ MB

In [ ]:
# exibindo os valores únicos da coluna 'Emissão / Remoção / Bunker'
emissoes_gases['Emissão / Remoção / Bunker'].unique()

array(['Emissão', 'Emissão NCI', 'Remoção NCI', 'Bunker', 'Remoção'],
      dtype=object)

In [ ]:
# filtrando linhas onde a coluna 'Emissão / Remoção / Bunker' é igual a 'Remoção NCI' ou 'Remoção'
(emissoes_gases['Emissão / Remoção / Bunker'] == 'Remoção NCI') | (emissoes_gases['Emissão / Remoção / Bunker'] == 'Remoção')

0         False
1         False
2         False
3         False
4         False
          ...
103307    False
103308    False
103309    False
103310    False
103311    False
Name: Emissão / Remoção / Bunker, Length: 103312, dtype: bool

In [ ]:
# filtrando diversos valores dentro de uma coluna usando o método isin() que é responsável por verificar se o valor da coluna está dentro de uma lista de valores
emissoes_gases[emissoes_gases['Emissão / Remoção / Bunker'].isin(['Remoção NCI', 'Remoção'])]

,Nível 1 - Setor,Nível 2,Nível 3,Nível 4,Nível 5,Nível 6,Emissão / Remoção / Bunker,Gás,Estado,Atividade Econômica,Produto,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
23520,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),RO,PEC,CAR/LEI/ALIM_BEBIDAS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-5.148931e+06,-5.457057e+06,-5.910369e+06,-6.431514e+06,-7.106344e+06,-7.885040e+06,-8.618762e+06,-9.097648e+06,-9.528928e+06,-1.009564e+07,-1.061215e+07,-1.137981e+07,-1.225676e+07,-1.360088e+07,-1.439432e+07,-1.481475e+07,-1.526265e+07,-1.541572e+07,-1.474137e+07,-1.428378e+07,-1.423277e+07,-1.427399e+07,-1.434540e+07,-1.499358e+07,-1.543196e+07,-1.567070e+07,-1.630063e+07,-1.702215e+07,-1.740074e+07,-1.771914e+07,-1.767632e+07,-1.838895e+07
23521,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),AC,PEC,CAR/LEI/ALIM_BEBIDAS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.788838e+06,-1.897475e+06,-2.026054e+06,-2.161615e+06,-2.348039e+06,-2.512975e+06,-2.671588e+06,-2.819946e+06,-2.969469e+06,-3.153655e+06,-3.308088e+06,-3.494499e+06,-3.827410e+06,-4.171793e+06,-4.420787e+06,-4.621123e+06,-4.666363e+06,-4.673402e+06,-4.708788e+06,-4.856662e+06,-5.061007e+06,-5.262222e+06,-5.382949e+06,-5.524659e+06,-5.632429e+06,-5.765030e+06,-5.867354e+06,-5.942076e+06,-6.022000e+06,-6.002147e+06,-6.035591e+06,-6.459079e+06
23522,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),AM,PEC,CAR/LEI/ALIM_BEBIDAS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.189654e+06,-1.118442e+06,-1.262502e+06,-1.454086e+06,-1.536762e+06,-1.497937e+06,-1.591582e+06,-1.821067e+06,-2.151739e+06,-2.288097e+06,-2.190817e+06,-2.231686e+06,-2.388050e+06,-2.625849e+06,-2.912366e+06,-3.213893e+06,-3.376536e+06,-3.237396e+06,-3.022441e+06,-3.200967e+06,-3.355014e+06,-3.431514e+06,-3.450455e+06,-3.540294e+06,-3.545724e+06,-3.924546e+06,-4.626541e+06,-4.874199e+06,-4.849173e+06,-4.959540e+06,-5.106806e+06,-5.809814e+06
23523,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),RR,PEC,CAR/LEI/ALIM_BEBIDAS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.926546e+05,-2.948908e+05,-3.221562e+05,-3.768267e+05,-4.055856e+05,-4.146538e+05,-4.404208e+05,-4.555405e+05,-4.988261e+05,-5.865328e+05,-6.497795e+05,-7.592651e+05,-9.408784e+05,-1.038577e+06,-1.122355e+06,-1.207625e+06,-1.284623e+06,-1.237594e+06,-1.218013e+06,-1.243515e+06,-1.288520e+06,-1.264494e+06,-1.260166e+06,-1.261895e+06,-1.371664e+06,-1.501452e+06,-1.507705e+06,-1.509919e+06,-1.609826e+06,-1.616980e+06,-1.518397e+06,-1.926000e+06
23524,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),PA,PEC,CAR/LEI/ALIM_BEBIDAS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.162867e+07,-1.218022e+07,-1.321234e+07,-1.416597e+07,-1.490071e+07,-1.617098e+07,-1.718269e+07,-1.835350e+07,-1.947202e+07,-2.023987e+07,-2.099544e+07,-2.319728e+07,-2.554603e+07,-2.680599e+07,-2.918278e+07,-3.041814e+07,-3.191642e+07,-3.331826e+07,-3.478299e+07,-3.498422e+07,-3.458375e+07,-3.485646e+07,-3.429279e+07,-3.317185e+07,-3.281628e+07,-3.350720e+07,-3.557183e+07,-3.755308e+07,-4.134614e+07,-4.229403e+07,-4.275448e+07,-4.443440e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102751,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pantanal,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR4,MS,AGROPEC,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.699000e+03,-4.822000e+03,-6.959000e+03,-6.977000e+03,-6.470000e+03,-5.753000e+03,-1.416300e+04,-2.144200e+04,-2.365000e+04,-2.376100e+04,-3.105400e+04,-3.609200e+04,-4.950200e+04,-6.529500e+04,-7.893400e+04,-7.502600e+04,-5.834400e+04,-5.674200e+04,-5.353100e+04,-5.177900e+04,-5.404500e+04,-6.042000e+04,-7.513000e+04,-7.911900e+04,-8.695900e+04,-9.201400e+04,-9.149400e+04,-9.630200e+04,-9.202000e+04,-9.762300e+04,-1.015020e+05,-1.008910e+05
102752,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pantanal,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR5,MT,AGROPEC,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-7.300000e+01,-2.390000e+02,-2.440000e+02,-5.960000e+02,-6.340000e+02,-6.930000e+02,-7.380000e+02,-1.053000e+03,-8.895000e+03,-9.758000e+03,-9.653000e+03,-9.630000e+03,-9.249000e+03,-9.651000e+03,-9.431000e+03,-9.523000e+03,-9.667000e+03,-1.000300e+04,-1.024200e+04,-1.027200e+04,-1.019100e+04,-1.046900e+04,-1.090400e+04,-1.104100e+04,-1.109500e+04
102753,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pantanal,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR5,MS,AGROPEC,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.699000e+03,-4.822000e+03,-6.959000e+03,-6.977000e+03,-6.470000e+03,-5.753000e+03,-1.416300e+04,-2.144200e+04,-2.365000e+04,-2.376100e+04,-3.105400e+04,-3.609200e+04,-4.950200e+04,-6.529500e+04,-7.893400e+04,-7.502600e+04,-5.834400e+04,-5.674200e+04,-5.353100e+04,-5.177900e+04,-5.404500e+04,-6.042000e+04,-7.513000e+04,-7.911900e+04,-8.695900e+04,-9.201400e+04,-9.149400e+04,-9.630200e+04,-9.202000e+04,-9.762300e+04,-1.015020e+05,-1.008910e+05
102754,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pantanal,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR6,MT,AGROPEC,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-7.300000e+01,-2.390000e+02,-2.440000e+02,-5.960000e+02,-6.340000e+02,-6.930000e+02,-7.380000e+02,-1.053000e+03,-8.895000e+03,-9.758000e+03,-9.653000e+03,-9.630000e+03,-9.249000e+03,-9.651000e+03,-9.431000e+03,-9.523000e+03,-9.667000e+03,-1.000300e+04,-1.024200e+04,-1.027200e+04,-1.019100e+04,-1.046900e+04,-1.090400e+04,-1.104100e+04,-1.109500e+04
102755,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pantanal,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR6,MS,AGROPEC,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.699000e+03,-4.822000e+03,-6.959000e+03,-6.977000e+03,-6.470000e+03,-5.753000e+03,-1.416300e+04,-2.144200e+04,-2.365000e+04,-2.376100e+04,-3.105400e+04,-3.609200e+04,-4.950200e+04,-6.529500e+04,-7.893400e+04,-7.502600e+04,-5.834400e+04,-5.674200e+04,-5.353100e+04,-5.177900e+04,-5.404500e+04,-6.042000e+04,-7.513000e+04,-7.911900e+04,-8.695900e+04,-9.201400e+04,-9.149400e+04,-9.630200e+04,-9.202000e+04,-9.762300e+04,-1.015020e+05,-1.008910e+05

In [ ]:
# utilizando o loc para selecionar linhas e colunas específicas
emissoes_gases.loc[emissoes_gases['Emissão / Remoção / Bunker'].isin(['Remoção NCI', 'Remoção']), 1970:2021]

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
23520,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-5.148931e+06,-5.457057e+06,-5.910369e+06,-6.431514e+06,-7.106344e+06,-7.885040e+06,-8.618762e+06,-9.097648e+06,-9.528928e+06,-1.009564e+07,-1.061215e+07,-1.137981e+07,-1.225676e+07,-1.360088e+07,-1.439432e+07,-1.481475e+07,-1.526265e+07,-1.541572e+07,-1.474137e+07,-1.428378e+07,-1.423277e+07,-1.427399e+07,-1.434540e+07,-1.499358e+07,-1.543196e+07,-1.567070e+07,-1.630063e+07,-1.702215e+07,-1.740074e+07,-1.771914e+07,-1.767632e+07,-1.838895e+07
23521,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.788838e+06,-1.897475e+06,-2.026054e+06,-2.161615e+06,-2.348039e+06,-2.512975e+06,-2.671588e+06,-2.819946e+06,-2.969469e+06,-3.153655e+06,-3.308088e+06,-3.494499e+06,-3.827410e+06,-4.171793e+06,-4.420787e+06,-4.621123e+06,-4.666363e+06,-4.673402e+06,-4.708788e+06,-4.856662e+06,-5.061007e+06,-5.262222e+06,-5.382949e+06,-5.524659e+06,-5.632429e+06,-5.765030e+06,-5.867354e+06,-5.942076e+06,-6.022000e+06,-6.002147e+06,-6.035591e+06,-6.459079e+06
23522,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.189654e+06,-1.118442e+06,-1.262502e+06,-1.454086e+06,-1.536762e+06,-1.497937e+06,-1.591582e+06,-1.821067e+06,-2.151739e+06,-2.288097e+06,-2.190817e+06,-2.231686e+06,-2.388050e+06,-2.625849e+06,-2.912366e+06,-3.213893e+06,-3.376536e+06,-3.237396e+06,-3.022441e+06,-3.200967e+06,-3.355014e+06,-3.431514e+06,-3.450455e+06,-3.540294e+06,-3.545724e+06,-3.924546e+06,-4.626541e+06,-4.874199e+06,-4.849173e+06,-4.959540e+06,-5.106806e+06,-5.809814e+06
23523,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.926546e+05,-2.948908e+05,-3.221562e+05,-3.768267e+05,-4.055856e+05,-4.146538e+05,-4.404208e+05,-4.555405e+05,-4.988261e+05,-5.865328e+05,-6.497795e+05,-7.592651e+05,-9.408784e+05,-1.038577e+06,-1.122355e+06,-1.207625e+06,-1.284623e+06,-1.237594e+06,-1.218013e+06,-1.243515e+06,-1.288520e+06,-1.264494e+06,-1.260166e+06,-1.261895e+06,-1.371664e+06,-1.501452e+06,-1.507705e+06,-1.509919e+06,-1.609826e+06,-1.616980e+06,-1.518397e+06,-1.926000e+06
23524,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.162867e+07,-1.218022e+07,-1.321234e+07,-1.416597e+07,-1.490071e+07,-1.617098e+07,-1.718269e+07,-1.835350e+07,-1.947202e+07,-2.023987e+07,-2.099544e+07,-2.319728e+07,-2.554603e+07,-2.680599e+07,-2.918278e+07,-3.041814e+07,-3.191642e+07,-3.331826e+07,-3.478299e+07,-3.498422e+07,-3.458375e+07,-3.485646e+07,-3.429279e+07,-3.317185e+07,-3.281628e+07,-3.350720e+07,-3.557183e+07,-3.755308e+07,-4.134614e+07,-4.229403e+07,-4.275448e+07,-4.443440e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102751,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.699000e+03,-4.822000e+03,-6.959000e+03,-6.977000e+03,-6.470000e+03,-5.753000e+03,-1.416300e+04,-2.144200e+04,-2.365000e+04,-2.376100e+04,-3.105400e+04,-3.609200e+04,-4.950200e+04,-6.529500e+04,-7.893400e+04,-7.502600e+04,-5.834400e+04,-5.674200e+04,-5.353100e+04,-5.177900e+04,-5.404500e+04,-6.042000e+04,-7.513000e+04,-7.911900e+04,-8.695900e+04,-9.201400e+04,-9.149400e+04,-9.630200e+04,-9.202000e+04,-9.762300e+04,-1.015020e+05,-1.008910e+05
102752,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-7.300000e+01,-2.390000e+02,-2.440000e+02,-5.960000e+02,-6.340000e+02,-6.930000e+02,-7.380000e+02,-1.053000e+03,-8.895000e+03,-9.758000e+03,-9.653000e+03,-9.630000e+03,-9.249000e+03,-9.651000e+03,-9.431000e+03,-9.523000e+03,-9.667000e+03,-1.000300e+04,-1.024200e+04,-1.027200e+04,-1.019100e+04,-1.046900e+04,-1.090400e+04,-1.104100e+04,-1.109500e+04
102753,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.699000e+03,-4.822000e+03,-6.959000e+03,-6.977000e+03,-6.470000e+03,-5.753000e+03,-1.416300e+04,-2.144200e+04,-2.365000e+04,-2.376100e+04,-3.105400e+04,-3.609200e+04,-4.950200e+04,-6.529500e+04,-7.893400e+04,-7.502600e+04,-5.834400e+04,-5.674200e+04,-5.353100e+04,-5.177900e+04,-5.404500e+04,-6.042000e+04,-7.513000e+04,-7.911900e+04,-8.695900e+04,-9.201400e+04,-9.149400e+04,-9.630200e+04,-9.202000e+04,-9.762300e+04,-1.015020e+05,-1.008910e+05
102754,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-7.300000e+01,-2.390000e+02,-2.440000e+02,-5.960000e+02,-6.340000e+02,-6.930000e+02,-7.380000e+02,-1.053000e+03,-8.895000e+03,-9.758000e+03,-9.653000e+03,-9.630000e+03,-9.249000e+03,-9.651000e+03,-9.431000e+03,-9.523000e+03,-9.667000e+03,-1.000300e+04,-1.024200e+04,-1.027200e+04,-1.019100e+04,-1.046900e+04,-1.090400e+04,-1.104100e+04,-1.109500e+04
102755,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.699000e+03,-4.822000e+03,-6.959000e+03,-6.977000e+03,-6.470000e+03,-5.753000e+03,-1.416300e+04,-2.144200e+04,-2.365000e+04,-2.376100e+04,-3.105400e+04,-3.609200e+04,-4.950200e+04,-6.529500e+04,-7.893400e+04,-7.502600e+04,-5.834400e+04,-5.674200e+04,-5.353100e+04,-5.177900e+04,-5.404500e+04,-6.042000e+04,-7.513000e+04,-7.911900e+04,-8.695900e+04,-9.201400e+04,-9.149400e+04,-9.630200e+04,-9.202000e+04,-9.762300e+04,-1.015020e+05,-1.008910e+05

In [ ]:
# utilizando o loc para selecionar linhas e colunas específicas e aplicando a função max() para obter o valor máximo dessas seleções
emissoes_gases.loc[emissoes_gases['Emissão / Remoção / Bunker'].isin(['Remoção NCI', 'Remoção']), 1970:2021].max()

1970    0.0
1971    0.0
1972    0.0
1973    0.0
1974    0.0
1975    0.0
1976    0.0
1977    0.0
1978    0.0
1979    0.0
1980    0.0
1981    0.0
1982    0.0
1983    0.0
1984    0.0
1985    0.0
1986    0.0
1987    0.0
1988    0.0
1989    0.0
1990    0.0
1991    0.0
1992    0.0
1993    0.0
1994    0.0
1995    0.0
1996    0.0
1997    0.0
1998    0.0
1999    0.0
2000    0.0
2001    0.0
2002    0.0
2003    0.0
2004    0.0
2005    0.0
2006    0.0
2007    0.0
2008    0.0
2009    0.0
2010    0.0
2011    0.0
2012    0.0
2013    0.0
2014    0.0
2015    0.0
2016    0.0
2017    0.0
2018    0.0
2019    0.0
2020    0.0
2021    0.0
dtype: float64

In [ ]:
# utilizando o loc para selecionar linhas onde a coluna 'Emissão / Remoção / Bunker' é igual a 'Bunker' e obtendo os valores únicos da coluna 'Estado'
emissoes_gases.loc[emissoes_gases['Emissão / Remoção / Bunker'] == 'Bunker', 'Estado'].unique()

array([nan], dtype=object)

In [ ]:
# removendo a coluna 'Emissão / Remoção / Bunker' do DataFrame  
emissoes_gases = emissoes_gases[emissoes_gases['Emissão / Remoção / Bunker'] == 'Emissão']
emissoes_gases

,Nível 1 - Setor,Nível 2,Nível 3,Nível 4,Nível 5,Nível 6,Emissão / Remoção / Bunker,Gás,Estado,Atividade Econômica,Produto,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Processos Industriais,Indústria Química,Produção de ABS,NaN,NaN,NaN,Emissão,COVNM (t),SP,OUTRA_IND,NaN,0.0,0.000,0.000,0.000,0.00,16.728,1.552576e+02,1.629552e+02,2.314992e+02,3.082848e+02,3.688864e+02,291.040,311.304,571.200,670.480,6.811333e+02,6.917867e+02,702.440,7.130933e+02,7.237467e+02,7.344000e+02,7.072000e+02,7.616000e+02,8.704000e+02,8.704000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600,897.600,897.600
1,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,N2O (t),SP,OUTRA_IND,NaN,6210.0,6116.580,7747.650,8276.580,9366.30,9675.720,1.299105e+04,1.389312e+04,1.448847e+04,1.459296e+04,1.437264e+04,13611.240,13854.240,14731.470,11670.480,1.025001e+04,1.193292e+04,11307.330,1.108269e+04,1.132488e+04,8.630000e+03,1.125000e+04,1.041000e+04,1.384000e+04,1.399000e+04,1.508000e+04,1.122000e+04,9.660000e+03,1.675000e+04,1.662000e+04,1.751000e+04,1.390000e+04,1.780000e+04,1.619000e+04,2.348000e+04,2.029000e+04,2.231000e+04,570.000000,370.000000,140.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000,130.000,130.000
2,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,CO (t),SP,OUTRA_IND,NaN,368.0,362.464,459.120,490.464,555.04,573.376,7.698400e+02,8.232960e+02,8.585760e+02,8.647680e+02,8.517120e+02,806.592,820.992,872.976,691.584,6.074080e+02,7.071360e+02,670.064,6.567520e+02,6.711040e+02,5.112160e+02,6.668160e+02,6.166080e+02,8.202240e+02,8.292000e+02,8.938240e+02,6.648640e+02,5.722720e+02,9.928800e+02,9.851520e+02,1.037792e+03,8.237760e+02,1.054896e+03,9.596640e+02,1.391328e+03,1.202352e+03,1.321824e+03,1421.808000,1360.336000,1395.136000,1380.576000,1380.576000,1380.576000,1380.576000,1380.576000,1380.576000,1380.576000,1380.576000,1380.576000,1380.576,1380.576,1380.576
3,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,NOx (t),SP,OUTRA_IND,NaN,115.0,113.270,143.475,153.270,173.45,179.180,2.405750e+02,2.572800e+02,2.683050e+02,2.702400e+02,2.661600e+02,252.060,256.560,272.805,216.120,1.898150e+02,2.209800e+02,209.395,2.052350e+02,2.097200e+02,1.597550e+02,2.083800e+02,1.926900e+02,2.563200e+02,2.591250e+02,2.793200e+02,2.077700e+02,1.788350e+02,3.102750e+02,3.078600e+02,3.243100e+02,2.574300e+02,3.296550e+02,2.998950e+02,4.347900e+02,3.757350e+02,4.130700e+02,444.315000,425.105000,435.980000,431.430000,431.430000,431.430000,431.430000,431.430000,431.430000,431.430000,431.430000,431.430000,431.430,431.430,431.430
4,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,CO2e (t) GWP-AR2,SP,OUTRA_IND,NaN,1925100.0,1896139.800,2401771.500,2565739.800,2903553.00,2999473.200,4.027226e+06,4.306867e+06,4.491426e+06,4.523818e+06,4.455518e+06,4219484.400,4294814.400,4566755.700,3617848.800,3.177503e+06,3.699205e+06,3505272.300,3.435634e+06,3.510713e+06,2.675300e+06,3.487500e+06,3.227100e+06,4.290400e+06,4.336900e+06,4.674800e+06,3.478200e+06,2.994600e+06,5.192500e+06,5.152200e+06,5.428100e+06,4.309000e+06,5.518000e+06,5.018900e+06,7.278800e+06,6.289900e+06,6.916100e+06,176700.000000,114700.000000,43400.000000,40300.000000,40300.000000,40300.000000,40300.000000,40300.000000,40300.000000,40300.000000,40300.000000,40300.000000,40300.000,40300.000,40300.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103241,Mudança de Uso da Terra e Floresta,Resíduos Florestais,Pantanal,NaN,Desmatamento,NaN,Emissão,CO2e (t) GWP-AR5,MS,AGROPEC,NaN,0.0,0.000,0.000,0.000,0.00,0.000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000000e+00,0.000000e+00,0.000,0.000000e+00,0.000000e+00,1.059422e+06,1.277008e+06,1.323244e+06,7.431760e+05,7.474880e+05,8.071820e+05,1.084467e+06,7.948060e+05,7.587290e+05,7.253150e+05,7.733190e+05,8.738200e+05,9.363680e+05,1.168532e+06,1.139252e+06,8.418460e+05,8.764810e+05,496519.000000,474598.000000,634125.000000,463846.000000,418623.000000,436935.000000,500067.000000,440030.000000,365272.000000,438422.000000,391113.000000,411738.000000,437039.000,871393.000,1004191.000
103242,Mudança de Uso da Terra e Floresta,Resíduos Florestais,Pantanal,NaN,Desmatamento,NaN,Emissão,CO2e (t) GWP-AR6,MT,AGROPEC,NaN,0.0,0.000,0.000,0.000,0.00,0.000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000000e+00,0.000000e+00,0.000,0.000000e+00,0.000000e+00,3.915400e+05,5.025740e+05,4.261840e+05,3.007070e+05,5.367440e+05,5.580310e+05,4.039540e+05,4.008500e+05,5.459820e+05,5.301760e+05,5.316160e+05,3.540120e+05,4.958120e+05,4.973950e+05,4.642580e+05,4.474000e+05,2.958930e+05,180879.000000,179956.000000,209904.000000,163289.000000,212900.000000,126806.000000,127558.000000,193758.000000,164585.000000,234509.000000,190412.000000,162919.000000,186091.000,368149.000,443120.000
103243,Mudança de Uso da Terra e Floresta,Resíduos Florestais,Pantanal,NaN,Desmatamento,NaN,Emissão,CO2e (t) GWP-AR6,MS,AGROPEC,NaN,0.0,0.000,0.000,0.000,0.00,0.000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000000e+00,0.000000e+00,0.000,0.000000e+00,0.000000e+00,1.063750e+06,1.282591e+06,1.328761e+06,7.462880e+05,7.507130e+05,8.105020e+05,1.089067e+06,7.981510e+05,7.619970e+05,7.284510e+05,7.766240e+05,8.776270e+05,9.405040e+05,1.173696e+06,1.144407e+06,8.456980e+05,8.804660e+05,498840.000000,476833.000000,637498.000000,466182.000000,420889.000000,439524.000000,502908.000000,442493.000000,367116.000000,440798.000000,393101.000000,413749.000000,439526.000,876637.000,1009968.000
103244,Mudança de Uso da Terra e Floresta,Resíduos Florestais,Pantanal,NaN,Desmatamento,NaN,Emissão,N2O (t),MT,AGROPEC,NaN,0.0,0.000,0.000,0.000,0.00,0.000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000000e+00,0.000000e+00,0.000,0.000000e+00,0.000000e+00,3.325803e+02,4.258408e+02,3.554489e+02,2.517572e+02,4.469413e+02,4.631265e+02,3.360912e+02,3.334968e+02,4.547440e+02,4.399988e+02,4.435472e+02,2.942102e+02,4.109443e+02,4.120846e+02,3.862364e+02,3.765834e+02,2.510332e+02,152.716017,152.359709,182.112429,141.312615,181.815704,108.441090,109.811199,166.680103,141.442361,201.556097,162.932751,137.219684,158.000,314.000,479.000
103245,Mudança de Uso da Terra e Floresta,Resíduos Florestais,Pantanal,NaN,Desmatamento,NaN,Emissão,N2O (t),MS,AGROPEC,NaN,0.0,0.000,0.000,0.000,0.00,0.000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000000e+00,0.000000e+00,0.000,0.000000e+00,0.000000e+00,9.065195e+02,1.133947e+03,1.144919e+03,6.445812e+02,6.590642e+02,6.936487e+02,9.471219e+02,6.911739e+02,6.682990e+02,6.401072e+02,6.782192e+02,7.742977e+02,8.361491e+02,1.043800e+03,1.031247e+03,7.665100e+02,7.954880e+02,457.833412,439.137586,630.106088,446.078410,420.404728,463.968255,517.078826,450.849218,352.160440,440.753215,378.038216,388.896998,452.000,935.000,1047.000

In [ ]:
# removendo a coluna 'Emissão / Remoção / Bunker' do DataFrame
emissoes_gases = emissoes_gases.drop(columns='Emissão / Remoção / Bunker')
emissoes_gases

,Nível 1 - Setor,Nível 2,Nível 3,Nível 4,Nível 5,Nível 6,Gás,Estado,Atividade Econômica,Produto,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Processos Industriais,Indústria Química,Produção de ABS,NaN,NaN,NaN,COVNM (t),SP,OUTRA_IND,NaN,0.0,0.000,0.000,0.000,0.00,16.728,1.552576e+02,1.629552e+02,2.314992e+02,3.082848e+02,3.688864e+02,291.040,311.304,571.200,670.480,6.811333e+02,6.917867e+02,702.440,7.130933e+02,7.237467e+02,7.344000e+02,7.072000e+02,7.616000e+02,8.704000e+02,8.704000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,8.976000e+02,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600000,897.600,897.600,897.600
1,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,N2O (t),SP,OUTRA_IND,NaN,6210.0,6116.580,7747.650,8276.580,9366.30,9675.720,1.299105e+04,1.389312e+04,1.448847e+04,1.459296e+04,1.437264e+04,13611.240,13854.240,14731.470,11670.480,1.025001e+04,1.193292e+04,11307.330,1.108269e+04,1.132488e+04,8.630000e+03,1.125000e+04,1.041000e+04,1.384000e+04,1.399000e+04,1.508000e+04,1.122000e+04,9.660000e+03,1.675000e+04,1.662000e+04,1.751000e+04,1.390000e+04,1.780000e+04,1.619000e+04,2.348000e+04,2.029000e+04,2.231000e+04,570.000000,370.000000,140.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000,130.000,130.000
2,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,CO (t),SP,OUTRA_IND,NaN,368.0,362.464,459.120,490.464,555.04,573.376,7.698400e+02,8.232960e+02,8.585760e+02,8.647680e+02,8.517120e+02,806.592,820.992,872.976,691.584,6.074080e+02,7.071360e+02,670.064,6.567520e+02,6.711040e+02,5.112160e+02,6.668160e+02,6.166080e+02,8.202240e+02,8.292000e+02,8.938240e+02,6.648640e+02,5.722720e+02,9.928800e+02,9.851520e+02,1.037792e+03,8.237760e+02,1.054896e+03,9.596640e+02,1.391328e+03,1.202352e+03,1.321824e+03,1421.808000,1360.336000,1395.136000,1380.576000,1380.576000,1380.576000,1380.576000,1380.576000,1380.576000,1380.576000,1380.576000,1380.576000,1380.576,1380.576,1380.576
3,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,NOx (t),SP,OUTRA_IND,NaN,115.0,113.270,143.475,153.270,173.45,179.180,2.405750e+02,2.572800e+02,2.683050e+02,2.702400e+02,2.661600e+02,252.060,256.560,272.805,216.120,1.898150e+02,2.209800e+02,209.395,2.052350e+02,2.097200e+02,1.597550e+02,2.083800e+02,1.926900e+02,2.563200e+02,2.591250e+02,2.793200e+02,2.077700e+02,1.788350e+02,3.102750e+02,3.078600e+02,3.243100e+02,2.574300e+02,3.296550e+02,2.998950e+02,4.347900e+02,3.757350e+02,4.130700e+02,444.315000,425.105000,435.980000,431.430000,431.430000,431.430000,431.430000,431.430000,431.430000,431.430000,431.430000,431.430000,431.430,431.430,431.430
4,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,CO2e (t) GWP-AR2,SP,OUTRA_IND,NaN,1925100.0,1896139.800,2401771.500,2565739.800,2903553.00,2999473.200,4.027226e+06,4.306867e+06,4.491426e+06,4.523818e+06,4.455518e+06,4219484.400,4294814.400,4566755.700,3617848.800,3.177503e+06,3.699205e+06,3505272.300,3.435634e+06,3.510713e+06,2.675300e+06,3.487500e+06,3.227100e+06,4.290400e+06,4.336900e+06,4.674800e+06,3.478200e+06,2.994600e+06,5.192500e+06,5.152200e+06,5.428100e+06,4.309000e+06,5.518000e+06,5.018900e+06,7.278800e+06,6.289900e+06,6.916100e+06,176700.000000,114700.000000,43400.000000,40300.000000,40300.000000,40300.000000,40300.000000,40300.000000,40300.000000,40300.000000,40300.000000,40300.000000,40300.000,40300.000,40300.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103241,Mudança de Uso da Terra e Floresta,Resíduos Florestais,Pantanal,NaN,Desmatamento,NaN,CO2e (t) GWP-AR5,MS,AGROPEC,NaN,0.0,0.000,0.000,0.000,0.00,0.000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000000e+00,0.000000e+00,0.000,0.000000e+00,0.000000e+00,1.059422e+06,1.277008e+06,1.323244e+06,7.431760e+05,7.474880e+05,8.071820e+05,1.084467e+06,7.948060e+05,7.587290e+05,7.253150e+05,7.733190e+05,8.738200e+05,9.363680e+05,1.168532e+06,1.139252e+06,8.418460e+05,8.764810e+05,496519.000000,474598.000000,634125.000000,463846.000000,418623.000000,436935.000000,500067.000000,440030.000000,365272.000000,438422.000000,391113.000000,411738.000000,437039.000,871393.000,1004191.000
103242,Mudança de Uso da Terra e Floresta,Resíduos Florestais,Pantanal,NaN,Desmatamento,NaN,CO2e (t) GWP-AR6,MT,AGROPEC,NaN,0.0,0.000,0.000,0.000,0.00,0.000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000000e+00,0.000000e+00,0.000,0.000000e+00,0.000000e+00,3.915400e+05,5.025740e+05,4.261840e+05,3.007070e+05,5.367440e+05,5.580310e+05,4.039540e+05,4.008500e+05,5.459820e+05,5.301760e+05,5.316160e+05,3.540120e+05,4.958120e+05,4.973950e+05,4.642580e+05,4.474000e+05,2.958930e+05,180879.000000,179956.000000,209904.000000,163289.000000,212900.000000,126806.000000,127558.000000,193758.000000,164585.000000,234509.000000,190412.000000,162919.000000,186091.000,368149.000,443120.000
103243,Mudança de Uso da Terra e Floresta,Resíduos Florestais,Pantanal,NaN,Desmatamento,NaN,CO2e (t) GWP-AR6,MS,AGROPEC,NaN,0.0,0.000,0.000,0.000,0.00,0.000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000000e+00,0.000000e+00,0.000,0.000000e+00,0.000000e+00,1.063750e+06,1.282591e+06,1.328761e+06,7.462880e+05,7.507130e+05,8.105020e+05,1.089067e+06,7.981510e+05,7.619970e+05,7.284510e+05,7.766240e+05,8.776270e+05,9.405040e+05,1.173696e+06,1.144407e+06,8.456980e+05,8.804660e+05,498840.000000,476833.000000,637498.000000,466182.000000,420889.000000,439524.000000,502908.000000,442493.000000,367116.000000,440798.000000,393101.000000,413749.000000,439526.000,876637.000,1009968.000
103244,Mudança de Uso da Terra e Floresta,Resíduos Florestais,Pantanal,NaN,Desmatamento,NaN,N2O (t),MT,AGROPEC,NaN,0.0,0.000,0.000,0.000,0.00,0.000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000000e+00,0.000000e+00,0.000,0.000000e+00,0.000000e+00,3.325803e+02,4.258408e+02,3.554489e+02,2.517572e+02,4.469413e+02,4.631265e+02,3.360912e+02,3.334968e+02,4.547440e+02,4.399988e+02,4.435472e+02,2.942102e+02,4.109443e+02,4.120846e+02,3.862364e+02,3.765834e+02,2.510332e+02,152.716017,152.359709,182.112429,141.312615,181.815704,108.441090,109.811199,166.680103,141.442361,201.556097,162.932751,137.219684,158.000,314.000,479.000
103245,Mudança de Uso da Terra e Floresta,Resíduos Florestais,Pantanal,NaN,Desmatamento,NaN,N2O (t),MS,AGROPEC,NaN,0.0,0.000,0.000,0.000,0.00,0.000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000000e+00,0.000000e+00,0.000,0.000000e+00,0.000000e+00,9.065195e+02,1.133947e+03,1.144919e+03,6.445812e+02,6.590642e+02,6.936487e+02,9.471219e+02,6.911739e+02,6.682990e+02,6.401072e+02,6.782192e+02,7.742977e+02,8.361491e+02,1.043800e+03,1.031247e+03,7.665100e+02,7.954880e+02,457.833412,439.137586,630.106088,446.078410,420.404728,463.968255,517.078826,450.849218,352.160440,440.753215,378.038216,388.896998,452.000,935.000,1047.000